blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: "âœ¨ Feature"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€"
    title: "[Feature] "
    labels: ["feature"]
    file: feature_request.yml

  - name: "ğŸ› Fix"
    description: "ë²„ê·¸ ìˆ˜ì • ìš”ì²­"
    title: "[Fix] "
    labels: ["bug"]
    file: bug_report.yml

  - name: "ğŸ§¹ Refactor"
    description: "ì½”ë“œ ë¦¬íŒ©í† ë§ ì œì•ˆ"
    title: "[Refactor] "
    labels: ["refactor"]
    file: refactor_request.yml

  - name: "ğŸ“ Docs"
    description: "ë¬¸ì„œ ì‘ì—… ìš”ì²­"
    title: "[Docs] "
    labels: ["documentation"]
    file: documentation_request.yml
